name: RepnDecomp
version: "1.3.1"
license: "GPL-3.0"
date: 2025-09-10
description: |
    Decompose representations of finite groups into irreducibles

authors:
    - name: Kaashif Hymabaccus
      url: https://kaashif.co.uk

maintainers:
    - name: Kaashif Hymabaccus
      url: https://kaashif.co.uk
    - name: Dmitrii Pasechnik
      url: https://pasechnik.info/dima

GAP: ">= 4.10"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.6.1"
      url: "https://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "GRAPE"
      version: ">= 4.8.1"
      url: "https://gap-packages.github.io/grape"

suggested-pkgs:
    - name: "IO"
      version: ">= 4.7.0"
      url: "https://gap-packages.github.io/io"

www: https://gap-packages.github.io/RepnDecomp
readme: README.md
packageinfo: https://gap-packages.github.io/RepnDecomp/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/RepnDecomp/releases/download/v1.3.1/RepnDecomp-1.3.1.tar.gz
    - name: .tar.bz2
      url: https://github.com/gap-packages/RepnDecomp/releases/download/v1.3.1/RepnDecomp-1.3.1.tar.bz2

abstract: |
    The <span class='pkgname'>RepnDecomp</span> package provides functions implementing various algorithms for decomposing linear representations of finite groups.

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    representations, groups.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>HP25</span>]   <b class='BibAuthor'>Hymabaccus, K. and Pasechnik, D.</b>,
     <i class='BibTitle'>RepnDecomp, Decompose representations of finite groups into irreducibles,
             Version 1.3.1</i>
     (<span class='BibYear'>2025</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/RepnDecomp">https://gap-packages.github.io/RepnDecomp</a></span>.
    </p>
    

bibtex: |
    @misc{ RepnDecomp,
      author =           {Hymabaccus, K. and Pasechnik, D.},
      title =            {{RepnDecomp},  {Decompose  representations  of  finite
                          groups into irreducibles}, {V}ersion 1.3.1},
      month =            {Sep},
      year =             {2025},
      note =             {GAP package},
      howpublished =     {\href      {https://gap-packages.github.io/RepnDecomp}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{RepnDecomp}}},
      keywords =         {representations; groups},
      printedkey =       {HP25}
    }

